#!/usr/bin/env python3
"""
Build docs/data/provenance.js: for every dataset the site reads, where it comes from.

  python tools/build_provenance.py

Nothing in it is typed by hand. For each dataset in tools/export_site_data.py (PAGES) it records:
  - the result table it is exported from (PAGES),
  - the notebook that writes that table (found by reading the save(..., "res_...") calls in notebooks/*.ipynb),
  - its sources (tools/public_manifest.json, the entry for results/<table>.csv),
  - the data checks on that table, with their number and status (results/res_dashboard_checks.csv, rows whose table_name is the table).
The source chips on the site (CMA.chip) read this file. tools/audit_public.py fails if a chip names a dataset without a check, or if a check here
is not in the checks the site shows.
"""
import csv
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))
from export_site_data import PAGES  # noqa: E402

OUT = ROOT / "docs" / "data" / "provenance.js"


def notebook_writers():
    writers = {}
    for nb in sorted((ROOT / "notebooks").glob("*.ipynb")):
        data = json.loads(nb.read_text(encoding="utf-8"))
        for cell in data["cells"]:
            if cell["cell_type"] != "code":
                continue
            src = "".join(cell["source"]) if isinstance(cell["source"], list) else cell["source"]
            # a table name passed as the last argument of save(...), which can span several lines
            for m in re.finditer(r"\"(res_[a-z0-9_]+)\"\s*\)", src):
                start = src.rfind("save(", 0, m.start())
                if start >= 0 and src.count("(", start, m.end()) == src.count(")", start, m.end()):
                    writers.setdefault(m.group(1), nb.name)
    return writers


def main():
    writers = notebook_writers()
    manifest = json.loads((ROOT / "tools" / "public_manifest.json").read_text(encoding="utf-8"))["files"]
    checks = list(csv.DictReader((ROOT / "results" / "res_dashboard_checks.csv").open(encoding="utf-8")))
    out = {}
    for page, datasets in PAGES.items():
        for key, table in datasets.items():
            entry = manifest.get(f"results/{table}.csv", {})
            rows = [c for c in checks if c["table_name"] == table]
            out[f"{page}.{key}"] = {
                "table": table,
                "notebook": writers.get(table, ""),
                "sources": entry.get("sources", []),
                "checks": [{"no": int(c["check_no"]), "description": c["description"], "status": c["status"]} for c in rows],
            }
    missing_nb = sorted(k for k, v in out.items() if not v["notebook"])
    payload = {"_meta": {"page": "provenance", "note": "generated by tools/build_provenance.py; do not edit by hand"}, "datasets": out}
    OUT.write_text("// Generated by tools/build_provenance.py. Do not edit by hand.\nwindow.CMA_DATA = window.CMA_DATA || {};\n"
                   "window.CMA_DATA.provenance = " + json.dumps(payload, separators=(",", ":"), ensure_ascii=True) + ";\n", encoding="utf-8", newline="\n")
    with_checks = sum(1 for v in out.values() if any(c["status"] != "INFO" for c in v["checks"]))
    print(f"wrote {OUT.relative_to(ROOT).as_posix()}: {len(out)} datasets, {with_checks} with at least one check" + (f"; no notebook found for {missing_nb}" if missing_nb else ""))


if __name__ == "__main__":
    main()
